-- ============================================================
-- SCRIPT COMPLETO DE CREACIÓN DE BASE DE DATOS
-- Proyecto: DB_Drako_IA
-- Total de tablas: 7
-- Fecha: 2026-10-08
-- ============================================================

-- ============================================================
-- EXTENSIONES NECESARIAS
-- ============================================================
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- ============================================================
-- TABLA 1: account
-- Descripción: Cuentas principales del sistema
-- ============================================================
CREATE TABLE IF NOT EXISTS account (
    account_id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(100) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ============================================================
-- TABLA 2: kitchen
-- Descripción: Tipos de cocina disponibles
-- ============================================================
CREATE TABLE IF NOT EXISTS kitchen (
    kitchen_id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    kitchen_type VARCHAR(50) NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ============================================================
-- TABLA 3: account_user
-- Descripción: Usuarios del sistema
-- ============================================================
CREATE TABLE IF NOT EXISTS account_user (
    user_id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    account_id BIGINT NOT NULL REFERENCES account(account_id) ON DELETE CASCADE,
    last_name VARCHAR(50) NOT NULL,
    name VARCHAR(50) NOT NULL,
    user_name VARCHAR(50) UNIQUE NOT NULL,
    user_password VARCHAR(255) NOT NULL,
    user_email VARCHAR(100) UNIQUE NOT NULL,
    user_home_address TEXT,
    is_active BOOLEAN DEFAULT TRUE,
    last_login TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ============================================================
-- TABLA 4: account_user_type_of_kitchen
-- Descripción: Relación N:N entre usuarios y tipos de cocina
-- ============================================================
CREATE TABLE IF NOT EXISTS account_user_type_of_kitchen (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT NOT NULL REFERENCES account_user(user_id) ON DELETE CASCADE,
    kitchen_id BIGINT NOT NULL REFERENCES kitchen(kitchen_id) ON DELETE CASCADE,
    assigned_date TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    is_primary BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UNIQUE(user_id, kitchen_id)
);

-- ============================================================
-- TABLA 5: account_user_linkable_devices
-- Descripción: Dispositivos enlazables a usuarios
-- ============================================================
CREATE TABLE IF NOT EXISTS account_user_linkable_devices (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT NOT NULL REFERENCES account_user(user_id) ON DELETE CASCADE,
    kitchen_id BIGINT NOT NULL REFERENCES kitchen(kitchen_id) ON DELETE CASCADE,
    device_serial VARCHAR(100) NOT NULL,
    device_status VARCHAR(20) DEFAULT 'active',
    linked_date TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    last_connection TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UNIQUE(user_id, device_serial)
);

-- ============================================================
-- TABLA 6: account_user_has
-- Descripción: Relaciones adicionales entre usuarios y otras entidades
-- ============================================================
CREATE TABLE IF NOT EXISTS account_user_has (
    has_id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT NOT NULL REFERENCES account_user(user_id) ON DELETE CASCADE,
    account_user_type_of_kitchen_id BIGINT REFERENCES account_user_type_of_kitchen(id) ON DELETE SET NULL,
    account_user_linkable_devices_id BIGINT REFERENCES account_user_linkable_devices(id) ON DELETE SET NULL,
    account_user_email VARCHAR(100),
    account_user_id BIGINT,
    has_type VARCHAR(50) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ============================================================
-- TABLA 7: audit_log
-- Descripción: Registro de auditoría de cambios
-- ============================================================
CREATE TABLE IF NOT EXISTS audit_log (
    log_id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    table_name VARCHAR(50) NOT NULL,
    operation VARCHAR(10) NOT NULL,
    user_id BIGINT,
    old_data JSONB,
    new_data JSONB,
    ip_address INET,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ============================================================
-- ÍNDICES PARA RENDIMIENTO
-- ============================================================

-- Índices de account_user
CREATE INDEX IF NOT EXISTS idx_account_user_account ON account_user(account_id);
CREATE INDEX IF NOT EXISTS idx_account_user_email ON account_user(user_email);
CREATE INDEX IF NOT EXISTS idx_account_user_username ON account_user(user_name);
CREATE INDEX IF NOT EXISTS idx_account_user_active ON account_user(is_active);

-- Índices de account_user_type_of_kitchen
CREATE INDEX IF NOT EXISTS idx_type_kitchen_user ON account_user_type_of_kitchen(user_id);
CREATE INDEX IF NOT EXISTS idx_type_kitchen_kitchen ON account_user_type_of_kitchen(kitchen_id);

-- Índices de account_user_linkable_devices
CREATE INDEX IF NOT EXISTS idx_devices_user ON account_user_linkable_devices(user_id);
CREATE INDEX IF NOT EXISTS idx_devices_kitchen ON account_user_linkable_devices(kitchen_id);
CREATE INDEX IF NOT EXISTS idx_devices_status ON account_user_linkable_devices(device_status);

-- Índices de account_user_has
CREATE INDEX IF NOT EXISTS idx_has_user ON account_user_has(user_id);
CREATE INDEX IF NOT EXISTS idx_has_type ON account_user_has(has_type);
CREATE INDEX IF NOT EXISTS idx_has_type_kitchen ON account_user_has(account_user_type_of_kitchen_id);
CREATE INDEX IF NOT EXISTS idx_has_devices ON account_user_has(account_user_linkable_devices_id);

-- Índices de audit_log
CREATE INDEX IF NOT EXISTS idx_audit_log_table ON audit_log(table_name);
CREATE INDEX IF NOT EXISTS idx_audit_log_operation ON audit_log(operation);
CREATE INDEX IF NOT EXISTS idx_audit_log_user ON audit_log(user_id);
CREATE INDEX IF NOT EXISTS idx_audit_log_created ON audit_log(created_at DESC);

-- ============================================================
-- VERIFICACIÓN FINAL
-- ============================================================

SELECT '✅ TODAS LAS TABLAS CREADAS EXITOSAMENTE' as mensaje;

-- Ver todas las tablas
SELECT 
    table_name,
    '✅' as estado
FROM information_schema.tables 
WHERE table_schema = 'public' 
AND table_type = 'BASE TABLE'
ORDER BY table_name;

-- Ver todas las relaciones (Foreign Keys)
SELECT
    tc.table_name as tabla_origen,
    kcu.column_name as columna_origen,
    ccu.table_name as tabla_destino,
    ccu.column_name as columna_destino
FROM information_schema.table_constraints tc
JOIN information_schema.key_column_usage kcu 
    ON tc.constraint_name = kcu.constraint_name
JOIN information_schema.constraint_column_usage ccu 
    ON ccu.constraint_name = tc.constraint_name
WHERE tc.constraint_type = 'FOREIGN KEY'
AND tc.table_schema = 'public'
ORDER BY tc.table_name;
